# Generated by Django 3.2.4 on 2021-06-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ManyToManyField(related_name='categoria', to='HOME.Categorias'),
        ),
    ]
