# Generated by Django 3.2.4 on 2021-06-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0002_auto_20210629_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.ManyToManyField(related_name='cat', to='HOME.Categorias'),
        ),
    ]
