# Generated by Django 3.2.4 on 2021-06-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0006_alter_productos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.ManyToManyField(to='HOME.Categorias'),
        ),
    ]
