# Generated by Django 3.2.4 on 2021-07-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0009_alter_productos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
